--- #YAML:1.0
name:                sf-upload
version:             4.08
abstract:            ~
license:             ~
author:              
    - Slaven Rezic (slaven@rezic.de)
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Crypt::SSLeay:                 0
    HTML::Parser:                  3
    HTML::Tree:                    0
    HTML::TreeBuilder:             0
    LWP::UserAgent:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
