#!/bin/sh

# Suppress kernel and modules messages (except panic) from appearing on the console
dmesg -n 1

#For UEFI
mount -o remount,rw /dev/ram0 /

/bin/HWMiniInit.sh

rm /dev/random
mknod -m 444 /dev/random c 1 9

haveged

echo "0" > /proc/sys/kernel/printk

/bin/m23install.sh
