.TH module_upgrade 1 "Red Hat, Inc."
.UC 4
.SH NAME
module_upgrade \- changes obsolete modules.conf entries to current ones

.SH SYNOPSIS
.B upgrader
.SH DESCRIPTION
.B module_upgrade
changes obsolete modules.conf mappings to new, correct ones. It
is for use when a module changes names. It reads the list
from /usr/share/hwdata/upgradelist.
.SH AUTHOR
Red Hat, Inc.
