#!/bin/bash

# Source debconf library.
. /usr/share/debconf/confmodule

# Returns 0, if run on UCS
UCS_detect()
{
	[ -f '/usr/sbin/udm' ]
	echo $?
}

if [ $(UCS_detect) -ne 0 ]
then
	db_input high m23/experimentalWarn || true
	db_go
fi

#
db_input high m23/configMySQL || true
db_go

if [ $(UCS_detect) -ne 0 ]
then
	db_input high m23/configDHCP || true
	db_go

	db_input high m23/configureSSH || true
	db_go
fi

db_input high m23/configureSquid || true
db_go

if [ $(UCS_detect) -ne 0 ]
then
	db_input high m23/configureSSL || true
	db_go

	db_input high m23/configureApache || true
	db_go
fi

db_input high m23/configureSudo || true
db_go

if [ $(UCS_detect) -ne 0 ]
then
	db_input high m23/configureBackupPC || true
	db_go
fi

if test `grep address /etc/network/interfaces | wc -l` -eq 0
then
	db_input high m23/warnDHCP || true
	db_go
fi