#!/bin/sh
#. /usr/share/debconf/confmodule
#db_set apache apache/document-root /m23/data+scripts
#db_set apache apache/enable-suexec true
#db_set apache apache/init true
#db_set apache apache/server-port 80
#db_set apache-common apache-shared/debconf-modules multiselect mod_log_config, mod_mime_magic, mod_mime, mod_negotiation, mod_status, mod_autoindex, mod_dir, mod_cgi, mod_userdir, mod_alias, mod_rewrite, mod_access, mod_auth, mod_expires, mod_setenvif, mod_ssl, mod_php4
#db_set apache-common apache-shared/restart false
#db_set dhcp3-server dhcp3-server/interfaces string
#db_set libapache-mod-php4 php4/update_apache_php_ini true
#db_set mysql-server mysql-server/postrm_remove_database false
#db_set mysql-server mysql-server/skip_networking false
#db_set mysql-server mysql-server/start_on_boot true
#db_set mysql-server mysql-server/want_chroot false
#db_set php4-mysql php4/extension_mysql_apache true
#db_set samba-common samba-common/character_set string
#db_set samba-common samba-common/codepage string
#db_set samba-common samba-common/dhcp false
#db_set samba-common samba-common/do_debconf true
#db_set samba-common samba-common/encrypt_passwords true
#db_set samba-common samba-common/workgroup string
#db_set squid squid/fix_lines true
