#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

# Returns 0, if run on UCS
UCS_detect()
{
	[ -f '/usr/sbin/udm' ]
	echo $?
}

if [ $(UCS_detect) -ne 0 ]
then
	db_input high m23-ldap/LDAPhint || true
	
	db_get slapd/password1
	if [ -z $RET ]
	then
		db_get m23-ldap/LDAPpass
		if [ -z $RET ]
		then
			#only ask for the LDAP admin password if it can't be read from the debconf
			db_input high m23-ldap/LDAPpass || true
		fi
	fi
fi

db_go