#!/bin/sh

#Uploads files to the new FRS of SF
#uploadFRS <file name with complete path> <release> <category>
uploadFRS()
{
	if [ $# -lt 3 ]
	then
		echo "uploadFRS: Missing parameters"
		echo "uploadFRS <file name with complete path> <release> <category>"
		echo "e.g. uploadFRS /mdk/doc/manual/pdf/m23-manual-de.pdf 2008-09-03 docs"
		echo "Press key to continue"
		read gaga
		exit 42
	fi

	file=$1
	release=$2
	category=$3


	tempDir="/tmp/m23SF-Upload$RANDOM"
	releaseDir="$tempDir/$release"
	mkdir -p "$releaseDir" #e.g. /tmp/m23-manual-de-2008-09-03
	#link the file to the temporary dir
	ln -s "$file" "$releaseDir"

	rsync -vPyrL -e ssh "$releaseDir" "hhabermann,m23@frs.sourceforge.net:/home/frs/project/m/m2/m23/$category"
	rm -r "$tempDir"
}


remoteDeleteOldDoubles()
{
echo "cd htdocs
cd m23inst
" >/tmp/ftpDel.cmd

echo "Erstelle Löschliste..."

echo "cd htdocs
cd m23inst
ls -1 *.deb" | sftp -b - hhabermann,m23@web.sourceforge.net | grep -v sftp | sort -r | awk -vFS='_' '
BEGIN {
last=""
}

{
	if (last != $1$3)
		last=$1$3
	else
		print("rm "$0);
}' >> /tmp/ftpDel.cmd

echo "Lösche doppelte Dateien..."
sftp -b /tmp/ftpDel.cmd hhabermann,m23@web.sourceforge.net
}

cd /m23inst




(md5sum -c all.md5 2>&1; echo $? > /tmp/ret) | tee /tmp/err
if test `cat /tmp/ret` -ne 0
then
	php -r 'mail("hauke@goos-habermann.de", "Uploadfehler: MD5", "MD5-Fehler:
	".file_get_contents("/tmp/err"));'
	echo "MD5-Fehler."
	exit 1
fi





(rsync -razPy --delete-after *.deb hhabermann,m23@web.sourceforge.net:/home/project-web/m23/htdocs/m23inst 2>&1; echo $? > /tmp/ret) | tee /tmp/err
if test `cat /tmp/ret` -ne 0
then
	php -r 'mail("hauke@goos-habermann.de", "Uploadfehler: Pakethochladen", "Fehler: Pakethochladen
	".file_get_contents("/tmp/err"));'
	echo "Fehler: Pakethochladen"
fi





(rsync --delete-after -razPy Release Release.gpg Packages Packages.gz Packages.bz2 hhabermann,m23@web.sourceforge.net:/home/project-web/m23/htdocs/m23inst 2>&1; echo $? > /tmp/ret) | tee /tmp/err
if test `cat /tmp/ret` -ne 0
then
	php -r 'mail("hauke@goos-habermann.de", "Uploadfehler: Hochladen Packages", "Fehler: Hochladen Packages*
	".file_get_contents("/tmp/err"));'
	echo "Fehler: Hochladen Packages*"
fi





(scp *.info hhabermann,m23@web.sourceforge.net:/home/project-web/m23/htdocs/m23patch/0.5.0/ 2>&1; echo $? > /tmp/ret) | tee /tmp/err

if test `cat /tmp/ret` -ne 0
then
	php -r 'mail("hauke@goos-habermann.de", "Uploadfehler:Hochladen info", "Fehler: Hochladen info
	".file_get_contents("/tmp/err"));'
	echo "Fehler: Hochladen info"
fi






#ssh hhabermann@shell.sf.net '/home/groups/m/m2/m23/bin/deleteOldDoubles /home/project-web/m23/htdocs/m23inst'
(remoteDeleteOldDoubles 2>&1; echo $? > /tmp/ret) | tee /tmp/err
if test `cat /tmp/ret` -ne 0
then
	php -r 'mail("hauke@goos-habermann.de", "Uploadfehler: Alte Pakete löschen", "Fehler: Alte Pakete löschen
	".file_get_contents("/tmp/err"));'
	echo "Fehler: Alte Pakete löschen"
fi

rm /tmp/err

#making backups to the FRS
for deb in `ls *.deb`
do
	nr=`echo $deb | php -r '
$name=fgets(STDIN);
$parts=preg_split("/[_-]+/",$name);
foreach ($parts as $part)
	if ($part > 100000)
	{
		echo($part);
		break;
	}
'`

#if it's no m23 package put it under addons
if [ -z $nr ]
then
	datum=`date +%Y-%m-%d`
	nr="addons-$datum"
fi

# 	(sf-upload -groupid 67156 -packageid 195044 -r $nr -f "$deb" -type .deb 2>&1; echo $? > /tmp/ret) | tee /tmp/err
	(uploadFRS "`pwd`/$deb" $nr packagebackups 2>&1; echo $? > /tmp/ret) | tee /tmp/err
	if test `cat /tmp/ret` -ne 0
	then
		php -r 'mail("hauke@goos-habermann.de", "Uploadfehler: FRS-Hochladen", "Fehler: FRS-Hochladen
		".file_get_contents("/tmp/err"));'
		echo "Fehler: FRS-Hochladen"
	fi
done


#check if the pool works
cd /m23test/
rm archivs/m23*
local-apt-update
local-apt-download -y m23 2>&1 | tee /tmp/poolCheck.log
php -r '
$f=fopen("/tmp/poolCheck.log","r");

$msg="";
while (!feof($f))
	$msg.=fgets($f);
mail("hauke@goos-habermann.de", "Uploadergebnis", "$msg");

fclose($f);
'
rm /tmp/poolCheck.log

m23DuplicateToFRS
